# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5df20f6011de0ae9c82f0e8ad629c1c00491f34e407cfe1dc35e99fcf6fa45a331165b9b8d5c213658c1e47b99020205d2f4e4902b10c60a4ebd2084286f7bf0

test:
  secret_key_base: e9468eed109760a09d6fae887765db007b96e8c343914d2bc3bc94bd4914d4289d11b3160a6c8ee571415e2c087bc3dfbc54554f61010c348ec3ea49724d374f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
